### PR TITLE
Hw 1

### PR DESCRIPTION
**Pull request by badyaxa**
HW_1 done

### CODE REVIEW

**Review by romanbobak — CHANGES_REQUESTED** [review]
Hi Bohdan. Please add **.gitignore** file to the root of the project. So git will ignore compiled java files and IntelliJ related files:
/target/
*.iml
/.idea/

Thank you!

**Review by romanbobak — CHANGES_REQUESTED** [review]
Hi Bohdan.
'.idea' folder is used by Intellij IDE to store it's metadata and doesn't contain any stuff related to the project itself. So, thus we do not need to push some files within this folder to the git repository.
Please place '.gitignore' file on the same level as 'pom.xml' with the following content:
```
/target/
*.iml
/.idea/
```
Thank you in advance!

**Comment by badyaxa** [comment]
please check

**Review by romanbobak — APPROVED** [review]
Hi Bohdan. Thanks for prompt response. Please merge PR into **main** branch. 
Thank you.

**Pull request merged**
